// A simple counter to generate sequential IDs
let nextId = 1;

// Re-creating the skills array with a unique ID for each item
export const skills = [
  // Cross-Functional Skills
  { id: nextId++, label: 'Communication Skills' },
  { id: nextId++, label: 'Problem-Solving' },
  { id: nextId++, label: 'Critical Thinking' },
  { id: nextId++, label: 'Adaptability' },
  { id: nextId++, label: 'Teamwork' },
  { id: nextId++, label: 'Leadership' },
  { id: nextId++, label: 'Time Management' },
  { id: nextId++, label: 'Data Analysis' },
  { id: nextId++, label: 'Strategic Thinking' },
  { id: nextId++, label: 'Negotiation' },
  { id: nextId++, label: 'Attention to Detail' },
  { id: nextId++, label: 'Decision-Making' },
  { id: nextId++, label: 'Project Management' },
  { id: nextId++, label: 'Emotional Intelligence' },
  { id: nextId++, label: 'Creative Thinking' },
  { id: nextId++, label: 'Conflict Resolution' },
  { id: nextId++, label: 'Business Acumen' },
  { id: nextId++, label: 'Presentation Skills' },
  { id: nextId++, label: 'Active Listening' },
  { id: nextId++, label: 'Networking' },

  // Engineering
  { id: nextId++, label: 'Computer Science' },
  { id: nextId++, label: 'Programming (Python, C++, Java)' },
  { id: nextId++, label: 'Troubleshooting' },
  { id: nextId++, label: 'CAD Software' },
  { id: nextId++, label: 'Systems Integration' },
  { id: nextId++, label: 'Mathematics' },
  { id: nextId++, label: 'Technical Documentation' },
  { id: nextId++, label: 'Electrical Engineering' },
  { id: nextId++, label: 'Mechanical Engineering' },
  { id: nextId++, label: 'DevOps' },
  { id: nextId++, label: 'Software Development' },
  { id: nextId++, label: 'Statistical Analysis' },
  { id: nextId++, label: 'Simulation and Modeling' },
  { id: nextId++, label: 'Quality Assurance' },
  { id: nextId++, label: 'Technical Knowledge' },

  // Business Development
  { id: nextId++, label: 'Market Research' },
  { id: nextId++, label: 'Relationship Management' },
  { id: nextId++, label: 'Prospecting' },
  { id: nextId++, label: 'Account Management' },
  { id: nextId++, label: 'Business Intelligence' },
  { id: nextId++, label: 'Contract Negotiation' },
  { id: nextId++, label: 'CRM Software (e.g., Salesforce, HubSpot)' },
  { id: nextId++, label: 'ROI Analysis' },
  { id: nextId++, label: 'Persuasion Skills' },
  { id: nextId++, label: 'Strategic Partnerships' },
  { id: nextId++, label: 'Competitive Analysis' },
  { id: nextId++, label: 'Sales Process Management' },
  { id: nextId++, label: 'Growth Strategy' },

  // Human Resources
  { id: nextId++, label: 'Recruitment' },
  { id: nextId++, label: 'Onboarding' },
  { id: nextId++, label: 'Employee Relations' },
  { id: nextId++, label: 'Training and Development' },
  { id: nextId++, label: 'Performance Management' },
  { id: nextId++, label: 'Compensation and Benefits' },
  { id: nextId++, label: 'HR Information Systems (HRIS)' },
  { id: nextId++, label: 'Intercultural Sensitivity' },
  { id: nextId++, label: 'Succession Planning' },
  { id: nextId++, label: 'Policy Formulation' },
  { id: nextId++, label: 'Workforce Planning' },
  { id: nextId++, label: 'Legal Compliance (e.g., Employment Law)' },
  { id: nextId++, label: 'Employee Engagement' },

  // Marketing
  { id: nextId++, label: 'Digital Marketing' },
  { id: nextId++, label: 'SEO (Search Engine Optimization)' },
  { id: nextId++, label: 'Content Marketing' },
  { id: nextId++, label: 'Social Media Management' },
  { id: nextId++, label: 'Email Marketing' },
  { id: nextId++, label: 'PPC (Pay-Per-Click) Advertising' },
  { id: nextId++, label: 'Market Segmentation' },
  { id: nextId++, label: 'Consumer Behavior Analysis' },
  { id: nextId++, label: 'Brand Management' },
  { id: nextId++, label: 'Marketing Automation' },
  { id: nextId++, label: 'UX/UI for Marketing' },
  { id: nextId++, label: 'Copywriting' },
  { id: nextId++, label: 'Campaign Management' },
  { id: nextId++, label: 'Analytics (Google Analytics, etc.)' },

  // Information Technology
  { id: nextId++, label: 'Cybersecurity' },
  { id: nextId++, label: 'Cloud Computing (AWS, Azure, GCP)' },
  { id: nextId++, label: 'Network Security' },
  { id: nextId++, label: 'Data Management' },
  { id: nextId++, label: 'Database Management (SQL)' },
  { id: nextId++, label: 'AI and Machine Learning' },
  { id: nextId++, label: 'Web Development' },
  { id: nextId++, label: 'Programming Languages (JavaScript, Python)' },
  { id: nextId++, label: 'UX/UI Design' },
  { id: nextId++, label: 'IT Automation' },
  { id: nextId++, label: 'Systems Administration' },
  { id: nextId++, label: 'Help Desk Support' },
  { id: nextId++, label: 'Data Visualization' },
  { id: nextId++, label: 'Enterprise Resource Planning (ERP)' },
  { id: nextId++, label: 'Blockchain' },

  // Operation Management
  { id: nextId++, label: 'Supply Chain Management' },
  { id: nextId++, label: 'Inventory Management' },
  { id: nextId++, label: 'Process Improvement' },
  { id: nextId++, label: 'Logistics' },
  { id: nextId++, label: 'Regulatory Compliance' },
  { id: nextId++, label: 'Budget Management' },
  { id: nextId++, label: 'Workflow Optimization' },
  { id: nextId++, label: 'Lean Manufacturing / Six Sigma' },
  { id: nextId++, label: 'Resource Allocation' },
  { id: nextId++, label: 'Vendor Management' },
  { id: nextId++, label: 'Forecasting' },
  { id: nextId++, label: 'Continuous Improvement' },

  // Sales
  { id: nextId++, label: 'Active Listening' },
  { id: nextId++, label: 'Empathy' },
  { id: nextId++, label: 'Product Knowledge' },
  { id: nextId++, label: 'Objection Handling' },
  { id: nextId++, label: 'Lead Qualification' },
  { id: nextId++, label: 'Sales Forecasting' },
  { id: nextId++, label: 'Closing Skills' },
  { id: nextId++, label: 'CRM Software' },
  { id: nextId++, label: 'Relationship Building' },
  { id: nextId++, label: 'Storytelling' },
  { id: nextId++, label: 'Strategic Selling' },
  { id: nextId++, label: 'Customer Success Management' },
  { id: nextId++, label: 'Cold Calling' },
  { id: nextId++, label: 'Sales Presentations' },

  // Design
  { id: nextId++, label: 'UI (User Interface) Design' },
  { id: nextId++, label: 'UX (User Experience) Design' },
  { id: nextId++, label: 'Adobe Creative Suite (Photoshop, Illustrator, InDesign)' },
  { id: nextId++, label: 'Figma' },
  { id: nextId++, label: 'Typography' },
  { id: nextId++, label: 'Branding' },
  { id: nextId++, label: 'Information Architecture' },
  { id: nextId++, label: 'Prototyping' },
  { id: nextId++, label: 'Wireframing' },
  { id: nextId++, label: 'User Research' },
  { id: nextId++, label: 'Graphic Design' },
  { id: nextId++, label: 'Visual Hierarchy' },
  { id: nextId++, label: 'Color Theory' },
];
